<a href="https://colab.research.google.com/github/jshuaaaa/TensorFlow-Notebook/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, were going to cover some of the most ufndamental concepts of tensors using TensorFlow

In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.2


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7.], [3.,2.], [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3,],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12],
                       [13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(1, 6, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Scalar: single number
Vector: a number with direction
Matrix: a 2-deminsional array of numbers
tensor: a n-dimensional array of numbers (where n can be any number)

### creating tensors with tf.variable

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
unchangeable_tensor, changeable_tensor


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [2,5],
                            [3,4]])
tf.random.set_seed(42) # Global level seed
tf.random.shuffle(not_shuffled, seed=1) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors


In [ ]:
#Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor set of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can run faster on a GPU for numerical computing

In [ ]:
import numpy as np
numpy_A = np.arange(1,51, dtype=np.int32)
numpy_A  # create a NumPy range between 1 and 25
# X = tf.constant(some_matrix)
# y = tf.constant(vector)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
      dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(5,10))
A

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]], dtype=int32)>

### Getting information from tensors
* Shape
* Rank
* Axis or dimension
* Size


In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("number of dimension:", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the zero axis:", rank_4_tensor.shape[0])
print("Elements a longt he last axis:", rank_4_tensor.shape[-1])
print('total number of elements in our tensor', tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
number of dimension: 4
Shape of tensor:  (2, 3, 4, 5)
Elements along the zero axis: 2
Elements a longt he last axis: 5
total number of elements in our tensor 120


### Indexing and expanding tensors

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],
                             [2,3]])
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expands the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

### Manipulating tensors (tensor operations)

In [ ]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# use tensor flow built in function
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
rank_5_tensor = tf.zeros(shape=[1,2,3,4,5])
rank_5_tensor.ndim

5

In [ ]:
tf.add(rank_5_tensor, 2)

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]]],


        [[[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]]]]], dtype=float32)>

**Matrix multiplication**

There are 2 rules to matrix multiplication

1. Inner dimensions must match (numbers on the inside must match)
2. The resulting matrix has the shape of the dimension (New size is same as outside numbers)

In [ ]:
#Matrix multiplication in tensor flow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor @ tensor # python syntax for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
a = tf.constant([[1,2,5],
                 [7,2,1]])

b = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57]], dtype=int32)>

In [ ]:
tf.reshape(a, shape=(3,2)) #reshapes tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 7],
       [2, 1]], dtype=int32)>

In [ ]:
tf.reshape(a, shape=(3,2)) @ tf.reshape(b, shape=(2,3)) # reshape and matrix multiply
# note that outputs are different based on matrix shape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [64, 32, 86],
       [13, 11, 20]], dtype=int32)>

In [ ]:
tf.transpose(a), tf.reshape(a, shape=(3,2)) # transpose flips axis, where as reshape is more customizable

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 7],
        [2, 2],
        [5, 1]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [5, 7],
        [2, 1]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(a), tf.transpose(b)) # note different results then reshape, as axis is flipped leaving to different values in each index

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[38, 55, 57],
       [16, 26, 18],
       [20, 37, 13]], dtype=int32)>

**The dot product**

In [ ]:
# perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(a), tf.transpose(b), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[38, 55, 57],
       [16, 26, 18],
       [20, 37, 13]], dtype=int32)>

Generally, when performing multiplication and two tensors you will usually transpose instead of reshaping if the axies doesnt line up to satisfy matrix multiplication rules

### Changing the datatype of a tensor

In [ ]:
B = tf.constant([1.7, 7.4])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

In [ ]:
D = tf.cast(B, dtype=tf.float16) #Change from float 32 to float 16(This makes it run faster)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregating tensors

Aggregating tnesors = condensing them from multiple valuies down to a smaller amount of values

In [ ]:
# get absolute values
D = tf.constant([-7, -10])
tf.abs(D) # note result is positive but tensor contains negative numbers

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

* Get minimum
* Get maximum
* Get mean
* Get sum

In [ ]:
E = tf.constant([[np.random.randint(0,100,size=50)], [np.random.randint(0,100,size=50)]])
E

<tf.Tensor: shape=(2, 1, 50), dtype=int32, numpy=
array([[[74, 79, 90, 97,  9, 56, 63, 74, 64, 30, 91,  3, 55, 46, 65, 71,
         98,  5, 61, 29, 17, 57, 33, 78,  2, 66, 77, 84, 96, 37, 80, 80,
         56, 86, 77, 33, 27, 80, 92, 68, 60, 83, 81, 65,  0, 62, 29, 48,
         78, 29]],

       [[62, 29, 84, 29, 28, 41, 74, 87, 69,  9, 74, 46, 22, 85, 51, 63,
         10, 36, 92, 22, 31, 50, 39, 69,  7, 42, 29, 21, 29, 21, 87, 98,
         94, 18, 59, 45,  9,  2, 89, 38, 23, 27, 72, 25, 45, 37, 88,  5,
         60, 45]]], dtype=int32)>

In [ ]:
# Find minmum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2366>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
E = tf.cast(E, dtype=tf.float32) # To reduce standard deviation and variance tensor must be a float 32
tf.math.reduce_std(E), tf.math.reduce_variance(E) # finds standard deviation and variance of a tensor

(<tf.Tensor: shape=(), dtype=float32, numpy=27.967045>,
 <tf.Tensor: shape=(), dtype=float32, numpy=782.15564>)

### Find the positional maximum and minimum





In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find positional maximum
tf.argmax(F) # Prints the postional maximum

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)] # Prints value

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F) == F[tf.argmax(F)] # above code works

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
F[tf.argmin(F)] # finds postional minimum

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
F[tf.argmin(F)] == tf.reduce_min(F) # above code works

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [ ]:
some_list = [0,1,2,3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4) # must note depth aswell

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values
tf.one_hot(some_list, depth=4, on_value="Epic", off_value='Not Epic')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Epic', b'Not Epic', b'Not Epic', b'Not Epic'],
       [b'Not Epic', b'Epic', b'Not Epic', b'Not Epic'],
       [b'Not Epic', b'Not Epic', b'Epic', b'Not Epic'],
       [b'Not Epic', b'Not Epic', b'Not Epic', b'Epic']], dtype=object)>

### Squaring,log,square root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H) # squares every index of the tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32)) # method requires not int type and makes square root of each index value

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))  # also requires float and performs log on each index value

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Exploring NumPy and tensors compatiblity

In [ ]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

numpy_J.dtype, tensor_J.dtype # notice how types slightly differ based on you create your tensor

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Aug 20 12:43:26 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

### 🛠 Exercises

In [ ]:
scalar = tf.constant([1,3])
vector = tf.constant([[1,3],
                      [1,3]])
matrix = tf.constant([[[1,3],
                       [1,3],
                       [5,2]]])
scalar,vector,matrix

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [1, 3]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
 array([[[1, 3],
         [1, 3],
         [5, 2]]], dtype=int32)>)

In [ ]:
A = tf.random.uniform(shape=[5,300]) # two random tensors with a shape of 5,300
B = tf.random.uniform(shape=[5,300])
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.48430407, 0.49744678, 0.99416983, ..., 0.21669662, 0.15572608,
        0.06326771],
       [0.556746  , 0.11630487, 0.23529184, ..., 0.8994404 , 0.99041045,
        0.98271215],
       [0.6525322 , 0.83911073, 0.05803096, ..., 0.53310204, 0.00212109,
        0.8451437 ],
       [0.30923676, 0.6099762 , 0.6871412 , ..., 0.2608255 , 0.75127125,
        0.3588164 ],
       [0.38995802, 0.2720102 , 0.8432734 , ..., 0.9887943 , 0.9503703 ,
        0.7824197 ]], dtype=float32)>

In [ ]:
tf.matmul(A,tf.transpose(B)) # matrix multiplication of A and B

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.44829 , 75.96834 , 74.57991 , 77.445   , 76.82603 ],
       [73.97283 , 77.39252 , 72.72565 , 75.0217  , 78.51088 ],
       [73.94036 , 76.209946, 70.51562 , 72.794136, 74.21949 ],
       [75.62225 , 75.05912 , 71.26631 , 74.911804, 76.21998 ],
       [73.51525 , 76.00629 , 72.99283 , 73.80384 , 75.27865 ]],
      dtype=float32)>

In [ ]:
tf.tensordot(A, tf.transpose(B), axes=1) # matrix multiplication using dot product of A and B

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.44829 , 75.96834 , 74.57991 , 77.445   , 76.82603 ],
       [73.97283 , 77.39252 , 72.72565 , 75.0217  , 78.51088 ],
       [73.94036 , 76.209946, 70.51562 , 72.794136, 74.21949 ],
       [75.62225 , 75.05912 , 71.26631 , 74.911804, 76.21998 ],
       [73.51525 , 76.00629 , 72.99283 , 73.80384 , 75.27865 ]],
      dtype=float32)>

In [ ]:
C = tf.random.uniform(shape=[224,224,3])
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.9140688 , 0.3813405 , 0.8801596 ],
        [0.08456445, 0.38843322, 0.07580185],
        [0.6676793 , 0.23105597, 0.0966804 ],
        ...,
        [0.85760427, 0.6673715 , 0.73771703],
        [0.19784546, 0.40160418, 0.06739688],
        [0.29501653, 0.01050925, 0.24931121]],

       [[0.24274635, 0.21261632, 0.52071834],
        [0.94324887, 0.11971116, 0.45951378],
        [0.3642788 , 0.00120926, 0.24548912],
        ...,
        [0.67721426, 0.5869106 , 0.79358804],
        [0.6816313 , 0.42342198, 0.5315577 ],
        [0.4536246 , 0.4407693 , 0.16460085]],

       [[0.95488167, 0.7154887 , 0.93927574],
        [0.60957193, 0.06503487, 0.5622928 ],
        [0.14480484, 0.6039567 , 0.2450732 ],
        ...,
        [0.9344679 , 0.13532853, 0.9384998 ],
        [0.06137526, 0.7844415 , 0.5744865 ],
        [0.0235157 , 0.03339612, 0.8182262 ]],

       ...,

       [[0.6177989 , 0.03471363, 0.32121015],
        [0.57

In [ ]:
tf.reduce_min(C), tf.reduce_max(C) # Research why min value is 1.27... etc

(<tf.Tensor: shape=(), dtype=float32, numpy=1.2755394e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999774>)

In [ ]:
D = tf.random.uniform(shape=[1,224,224,3])
D.shape

TensorShape([1, 224, 224, 3])

In [ ]:
D_squeezed = tf.squeeze(D)
D_squeezed.shape # squeezed out the first dimension

TensorShape([224, 224, 3])

In [ ]:
E = tf.random.uniform(shape=[10])
E

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.19366539, 0.8673382 , 0.4999628 , 0.8162403 , 0.27250051,
       0.39928854, 0.55092895, 0.9918773 , 0.83245814, 0.84370303],
      dtype=float32)>

In [ ]:
tf.argmax(E), tf.argmin(E), E[tf.argmin(E)], E[tf.argmax(E)] # finds maxs and mins of index and the values of each

(<tf.Tensor: shape=(), dtype=int64, numpy=7>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.19366539>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9918773>)

In [ ]:
E = tf.cast(E, dtype=tf.int32) # cant encode floats must be integers!
tf.one_hot(E, depth=3)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)>

### Create a tensorflow function sequence that calculates grocery bill for the month and for the year!

In [ ]:
grocery = tf.constant(np.random.randint(0,30,size=10)) # grocery list of 10 items and with numerical values as theoritcal prices
grocery

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1, 12, 21, 21, 19, 24, 11, 26,  5,  1])>

In [ ]:
# For this problem we will asume you go to the grocery store once a week
week = tf.reduce_sum(grocery).numpy()
week

141

In [ ]:
# Next step would be to calculate monthly expenses
month = week * 4
month

564

In [ ]:
# Yearly costs
year = month * 12
year

6768

In [ ]:
print("You will spend $", week , " a week and $" , month , " a month and $" , year ," a year on groceries")
print("Thats a lot of money!")

You will spend $ 141  a week and $ 564  a month and $ 6768  a year on groceries
Thats a lot of money!
